engishop_admin:
    resource: "@EngiShopBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

engishop_front:
    resource: "@EngiShopBundle/Resources/config/routing_front.yml"
    prefix:   /
