engishop_admin_category:
    resource: "@EngiShopBundle/Resources/config/admin/category.yml"
    prefix:   /category

engishop_admin_product:
    resource: "@EngiShopBundle/Resources/config/admin/product.yml"
    prefix:   /product

engishop_admin_user:
    resource: "@EngiShopBundle/Resources/config/admin/user.yml"
    prefix:   /user

engishop_admin_discount_code:
    resource: "@EngiShopBundle/Resources/config/admin/discount_code.yml"
    prefix:   /discount-code

engishop_admin_order:
    resource: "@EngiShopBundle/Resources/config/admin/order.yml"
    prefix:   /order

engishop_admin_login:
    path:     /login
    defaults: { _controller: EngiShopBundle:AdminSecurity:login }

engishop_admin_login_check:
    path: /login_check

engishop_admin_logout:
    path: /logout

engishop_admin_homepage:
    path: /
    defaults: { _controller: EngiShopBundle:AdminIndex:index }
