engishop_front_category:
    resource: "@EngiShopBundle/Resources/config/front/category.yml"
    prefix:   /kategoria

engishop_front_product:
    resource: "@EngiShopBundle/Resources/config/front/product.yml"
    prefix:   /

engishop_front_cart:
    resource: "@EngiShopBundle/Resources/config/front/cart.yml"
    prefix:   /koszyk

engishop_front_order:
    resource: "@EngiShopBundle/Resources/config/front/order.yml"
    prefix:   /zamowienie

engishop_front_user:
    resource: "@EngiShopBundle/Resources/config/front/user.yml"
    prefix:   /konto

engishop_front_post:
    resource: "@EngiShopBundle/Resources/config/front/post.yml"
    prefix: /blog



engishop_front_user_register:
    path: /rejestracja
    defaults: { _controller: EngiShopBundle:User:register }

engishop_front_login:
    path:     /login
    defaults: { _controller: EngiShopBundle:Security:login }

engishop_front_login_check:
    path: /login_check

engishop_front_logout:
    path: /logout

engishop_front_homepage:
    path: /
    defaults: { _controller: EngiShopBundle:Index:index }