parameters:
    security.exception_listener.class: EngiShopBundle\Security\Firewall\ExceptionListener

services:
    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }

    engishop.password_encoder:
        class: EngiShopBundle\Services\PasswordEncoder
        arguments:
            - @security.encoder_factory

    engishop.category_helper:
        class: EngiShopBundle\Services\CategoryHelper
        arguments:
            - @doctrine.orm.entity_manager

    engishop.cart_helper:
        class: EngiShopBundle\Services\CartHelper
        arguments:
            - @security.authorization_checker
            - @security.token_storage
