security:
    providers:
        admin:
            memory:
                users:
                    admin: { password: pass, roles: 'ROLE_ADMIN' }
        front:
            entity: { class: EngiShopBundle:User }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern:  ^/admin/login$
            security: false

        admin_area:
            pattern:   ^/admin
            provider: admin
            form_login:
                login_path: engishop_admin_login
                check_path: engishop_admin_login_check
            logout:
                path:   engishop_admin_logout
                target: /admin
        default:
            anonymous: ~

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext    # admin provider
        EngiShopBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }