EngiShopBundle\Entity\Category:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: slug

EngiShopBundle\Entity\File:
    properties:
        name:
            - NotBlank:
                message: Ta wartość nie powinna być pusta.
        file:
            - File:
                maxSize: 6000000

EngiShopBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: slug

    properties:
        slug:
            - NotNull:
                message: Ta wartość nie powinna być pusta.
            - Regex:
                message: Ta wartość nie jest poprawnym adresem.
                pattern: /^[a-zA-Z0-9_\-\+]+$/