engishop_front_product_show:
    path: /{slug}
    defaults: { _controller: EngiShopBundle:Product:show }
    requirements:
        slug: ^(?!login$)(?!logout$)(?!login_check$)(?!cart)(?!profile)([a-zA-Z0-9_\-\+]+)$