engishop_front_product_show:
    path: /{slug}
    defaults: { _controller: EngiShopBundle:Product:show }
    requirements:
        slug: ^(?!login$)(?!rejestracja)(?!logout$)(?!login_check$)(?!koszyk)(?!zamowienie)(?!konto)([a-zA-Z0-9_\-\+]+)$