engishop_admin_category:
    path: /
    defaults: { _controller: EngiShopBundle:AdminCategory:index }

engishop_admin_category_new:
    path: /new
    defaults: { _controller: EngiShopBundle:AdminCategory:new }

engishop_admin_category_edit:
    path: /edit/{id}
    defaults: { _controller: EngiShopBundle:AdminCategory:edit }
    requirements:
        id:  \d+

engishop_admin_category_toggle:
    path: /toggle/{id}
    defaults: { _controller: EngiShopBundle:AdminCategory:toggle }
    methods:  [POST]
    requirements:
        id:  \d+

engishop_admin_category_delete:
    path: /delete/{id}
    defaults: { _controller: EngiShopBundle:AdminCategory:delete }
    requirements:
        id:  \d+