engishop_admin_category:
    path: /
    defaults: { _controller: engishop_adminBundle:Category:index }

engishop_admin_category_new:
    path: /new
    defaults: { _controller: engishop_adminBundle:Category:new }

engishop_admin_category_edit:
    path: /edit/{id}
    defaults: { _controller: engishop_adminBundle:Category:edit }
    requirements:
        id:  \d+

engishop_admin_category_toggle:
    path: /toggle/{id}
    defaults: { _controller: engishop_adminBundle:Category:toggle }
    methods:  [POST]
    requirements:
        id:  \d+

engishop_admin_category_delete:
    path: /delete/{id}
    defaults: { _controller: engishop_adminBundle:Category:delete }
    requirements:
        id:  \d+