engishop_admin_product:
    path: /
    defaults: { _controller: EngiShopBundle:AdminProduct:index }

engishop_admin_product_new:
    path: /new
    defaults: { _controller: EngiShopBundle:AdminProduct:new }

engishop_admin_product_edit:
    path: /edit/{id}
    defaults: { _controller: EngiShopBundle:AdminProduct:edit }
    requirements:
        id:  \d+

engishop_admin_product_toggle:
    path: /toggle/{id}
    defaults: { _controller: EngiShopBundle:AdminProduct:toggle }
    methods:  [POST]
    requirements:
        id:  \d+

engishop_admin_product_delete:
    path: /delete/{id}
    defaults: { _controller: EngiShopBundle:AdminProduct:delete }
    methods:  [POST]
    requirements:
        id:  \d+

engishop_admin_product_delete_image:
    path: /delete-image/{id}
    defaults: { _controller: EngiShopBundle:AdminProduct:deleteImage }
    methods:  [POST]
    requirements:
        id:  \d+