<?php

namespace EngiShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getActiveCategories()
    {
        return $this->findBy(['active' => true], ['name' => 'asc']);
    }
}
