<?php

namespace EngiShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderClassRepository extends EntityRepository
{
}
