<?php

namespace EngiShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderClassRepository extends EntityRepository
{
    public function getAwaitingOrdersCount()
    {
        return $this->createQueryBuilder('o')->select('COUNT(o.id)')->where('o.inProcess = 0')->andWhere('o.completed = 0')->getQuery()->getSingleScalarResult();
    }
}
