<?php

namespace EngiShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getActiveProducts()
    {
        return $this->findBy(['active' => true], ['name' => 'asc']);
    }

    public function getFeaturedProducts()
    {
        return $this->findBy(['active' => true, 'featured' => true], ['name' => 'asc']);
    }
}
